version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mydb
    networks: 
    - mynetwork
    volumes: 
    - /data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root@121
    - MYSQL_DATABASE=blogdb
    - MYSQL_USER=rohit
    - MYSQL_PASSWORD=root@121

  wp:
    depends_on:
    - db
    image: wordpress:latest
    container_name: mywp1
    networks: 
    - mynetwork
    ports: 
    - 8080:80
    environment:
    - WORDPRESS_DB_HOST=mydb
    - WORDPRESS_DB_USER=rohit
    - WORDPRESS_DB_PASSWORD=rohit@121
    - WORDPRESS_DB_NAME=blogdb

networks:
  mynetwork:
    driver: bridge